api = "0.7"

[buildpack]
  id = "deno-buildpack"
  version = "dev"
  homepage = "https://runway.planetary-quantum.com"
  description = "A deno buildpack (for runway)"

[metadata]
  include-files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "make build"

[[stacks]]
  id = "*"
