api = "0.7"

[buildpack]
  id = "deno-buildpack"
  version = "__replace__"
  homepage = "https://www.runway.horse/docs/"
  description = "A deno buildpack (for runway)"

[metadata]
  include-files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "make build"

[[stacks]]
  id = "*"
