---
name: pr

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: "r.planetary-quantum.com"
      DOCKER_REPO: "buildpacks"
      BP_BUILD_DIR: "./build"
    outputs:
      name: ${{ steps.setup.outputs.package }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: buildpacks/github-actions/setup-tools@v5.9.3
      - uses: buildpacks/github-actions/setup-pack@v5.9.3
      - id: setup
        shell: bash
        run: |
          PACKAGE="${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/deno"
          echo "package=${PACKAGE}" >> $GITHUB_OUTPUT
          echo "version=dev" >> $GITHUB_OUTPUT
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: build --snapshot --clean
      - run: make prep VERSION=${{ steps.setup.outputs.version }}
      - working-directory: ${{ env.BP_BUILD_DIR }}
        run: |
          pack -v \
            buildpack \
            package \
            ${{ steps.setup.outputs.package }}:dev
      - run: |
          docker save ${{ steps.setup.outputs.package }}:dev -o buildpack.tar
      - uses: actions/upload-artifact@v4
        with:
          name: buildpack
          path: buildpack.tar
          retention-days: 1

  smoke:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      BUILDER: paketobuildpacks/builder-jammy-base:latest
    strategy:
      matrix:
        test: [deno, not-deno]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: buildpack
      - run: docker load -i buildpack.tar
      - run: docker image ls
      - uses: buildpacks/github-actions/setup-tools@v5.9.3
      - uses: buildpacks/github-actions/setup-pack@v5.9.3
      - run: |
          make setup \
            builder=${{ env.BUILDER }}
      - run: |
          make smoke-${{ matrix.test }} \
            buildpack=${{ needs.build.outputs.name }}:dev
