---
name: pr

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: "r.planetary-quantum.com"
      DOCKER_REPO: "buildpacks"
    outputs:
      name: ${{ steps.extract-package.outputs.package }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: buildpacks/github-actions/setup-tools@v5.9.3
      - uses: buildpacks/github-actions/setup-pack@v5.9.3
      - id: extract-package
        shell: bash
        run: |
          BP_ID="$(cat buildpack.toml | yj -t | jq -r .buildpack.id)"
          PACKAGE="${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/$(echo "$BP_ID" | sed 's/\//_/g')"
          echo "package=${PACKAGE}" >> $GITHUB_OUTPUT
      - run: sed -i.bak -E "s/__replace__/dev/" buildpack.toml
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          install-only: true
      - run: make build
      - run: |
          cp dist/build_linux_amd64_v1/build ./bin/build
          cp dist/detect_linux_amd64_v1/detect ./bin/detect
      - run: |
          pack -v \
            buildpack \
            package \
            ${{ steps.extract-package.outputs.package }}:dev
      - run: |
          docker save ${{ steps.extract-package.outputs.package }}:dev -o buildpack.tar
      - name: Upload buildpack artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildpack
          path: buildpack.tar
          retention-days: 1

  smoke:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      BUILDER: paketobuildpacks/builder-jammy-base:latest
    strategy:
      matrix:
        test: [deno, not-deno, deno2-serve]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: buildpack
      - run: docker load -i buildpack.tar
      - run: docker image ls
      - uses: buildpacks/github-actions/setup-tools@v5.9.3
      - uses: buildpacks/github-actions/setup-pack@v5.9.3
      - run: |
          make setup \
            builder=${{ env.BUILDER }}
      - run: |
          make smoke-${{ matrix.test }} \
            builder=${{ env.BUILDER }} \
            buildpack=${{ needs.build.outputs.name }}:dev
