---
name: pr

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: "r.planetary-quantum.com"
      DOCKER_REPO: "buildpacks"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: buildpacks/github-actions/setup-tools@v5.8.9
      - uses: buildpacks/github-actions/setup-pack@v5.8.9
      - id: extract-package
        shell: bash
        run: |
          BP_ID="$(cat buildpack.toml | yj -t | jq -r .buildpack.id)"
          PACKAGE="${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/$(echo "$BP_ID" | sed 's/\//_/g')"
          echo "package=${PACKAGE}" >> $GITHUB_OUTPUT
      - run: sed -i.bak -E "s/__replace__/dev/" buildpack.toml
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          install-only: true
      - run: make build
      - run: |
          cp dist/build_linux_amd64_v1/build ./bin/build
          cp dist/detect_linux_amd64_v1/detect ./bin/detect
      - run: |
          pack -v \
            buildpack \
            package \
            ${{ steps.extract-package.outputs.package }}:dev
      - run: |
          make setup \
            builder=paketobuildpacks/builder:tiny
      - run: |
          make smoke \
            buildpack=${{ steps.extract-package.outputs.package }}:dev
