---
name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: "r.planetary-quantum.com"
      DOCKER_REPO: "buildpacks"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
          cache: false
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.BP_QUANTUM_DOCKER_USERNAME }}
          password: ${{ secrets.BP_QUANTUM_DOCKER_PASSWORD }}
      - uses: buildpacks/github-actions/setup-tools@b4faaabcd9dbc5fa332451ae33bce8b583f3ec1b # v5.12.0
      - uses: buildpacks/github-actions/setup-pack@b4faaabcd9dbc5fa332451ae33bce8b583f3ec1b # v5.12.0
      - id: version
        shell: bash
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT
      - id: setup
        shell: bash
        run: |
          PACKAGE="${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/deno"
          echo "package=${PACKAGE}" >> $GITHUB_OUTPUT
      - uses: goreleaser/goreleaser-action@e24998b8b67b290c2fa8b7c14fcfa7de2c5c9b8c # v7
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make prep VERSION=${VERSION}
        env:
          VERSION: ${{ steps.version.outputs.version }}
      - working-directory: build
        run: |
          pack buildpack package \
            --target linux/amd64 \
            --target linux/arm64 \
            --publish ${PACKAGE}:${VERSION}
        env:
          PACKAGE: ${{ steps.setup.outputs.package }}
          VERSION: ${{ steps.version.outputs.version }}
