---
name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: "r.planetary-quantum.com"
      DOCKER_REPO: "buildpacks"
    steps:
      - id: load-registry-credentials
        uses: 1password/load-secrets-action@92467eb28f72e8255933372f1e0707c567ce2259 # v4.0.0
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_RUNWAYOSS_SERVICE_ACCOUNT }}
          REGISTRY_USERNAME: op://RunwayOSS/robot-harbor-buildpacks/username
          REGISTRY_PASSWORD: op://RunwayOSS/robot-harbor-buildpacks/password
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
          cache: false
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ steps.load-registry-credentials.outputs.REGISTRY_USERNAME }}
          password: ${{ steps.load-registry-credentials.outputs.REGISTRY_PASSWORD }}
      - uses: buildpacks/github-actions/setup-tools@812ff667850b930be2217c48e1f980e71bd3e14f # v5.12.3
      - uses: buildpacks/github-actions/setup-pack@812ff667850b930be2217c48e1f980e71bd3e14f # v5.12.3
      - id: version
        shell: bash
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT
      - id: setup
        shell: bash
        run: |
          PACKAGE="${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/deno"
          echo "package=${PACKAGE}" >> $GITHUB_OUTPUT
      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make prep VERSION=${VERSION}
        env:
          VERSION: ${{ steps.version.outputs.version }}
      - working-directory: build
        run: |
          pack buildpack package \
            --target linux/amd64 \
            --target linux/arm64 \
            --publish ${PACKAGE}:${VERSION}
        env:
          PACKAGE: ${{ steps.setup.outputs.package }}
          VERSION: ${{ steps.version.outputs.version }}
