---
name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: "r.planetary-quantum.com"
      DOCKER_REPO: "buildpacks"
    steps:
      - id: load-registry-credentials
        uses: 1password/load-secrets-action@3a12b0ab99d9cd590a3e9b5a90ea017210ed9556 # v4.0.1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_RUNWAYOSS_SERVICE_ACCOUNT }}
          REGISTRY_USERNAME: op://RunwayOSS/robot-harbor-buildpacks/username
          REGISTRY_PASSWORD: op://RunwayOSS/robot-harbor-buildpacks/password
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: false
      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ steps.load-registry-credentials.outputs.REGISTRY_USERNAME }}
          password: ${{ steps.load-registry-credentials.outputs.REGISTRY_PASSWORD }}
      - uses: buildpacks/github-actions/setup-tools@c1c71086a0e89a65c04ea113390227fd7f05d9df # v6.0.0
      - uses: buildpacks/github-actions/setup-pack@c1c71086a0e89a65c04ea113390227fd7f05d9df # v6.0.0
      - id: version
        shell: bash
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT
      - id: setup
        shell: bash
        run: |
          PACKAGE="${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/deno"
          echo "package=${PACKAGE}" >> $GITHUB_OUTPUT
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make prep VERSION=${VERSION}
        env:
          VERSION: ${{ steps.version.outputs.version }}
      - working-directory: build
        run: |
          pack buildpack package \
            --target linux/amd64 \
            --target linux/arm64 \
            --publish ${PACKAGE}:${VERSION}
        env:
          PACKAGE: ${{ steps.setup.outputs.package }}
          VERSION: ${{ steps.version.outputs.version }}
